name: Deploy Entire Application

on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches:
      - main

jobs:
  deploy_frontend:
    name: Build & Deploy Angular Frontend to S3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies & Build Angular App
        working-directory: ./frontend
        run: |
          npm install
          npm run build --prod

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: './frontend/dist/filemanage-frontend/browser' # Adjust the path if necessary

  deploy_backend:
    name: Deploy Laravel Backend to EC2
    runs-on: ubuntu-latest
    needs: deploy_frontend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Laravel Dependencies
        working-directory: ./backend
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Prepare Deployment Package
        working-directory: ./backend
        run: |
          zip -r ../backend.zip *
          echo "Listing parent directory:"
          ls -la ..

      - name: Set up SSH key for SCP
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Copy Deployment Package to EC2 using native scp
        run: |
          scp -o StrictHostKeyChecking=no backend.zip ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~




      - name: List Root Directory
        run: ls -la ..
      
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd /var/www/html/filemanage
            rm -rf *
            unzip -o ~/backend.zip -d /var/www/html/filemanage
            cd /var/www/html/filemanage
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force



