name: CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy_frontend:
    name: Build & Deploy Angular Frontend to S3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'


      - name: Install Dependencies & Build Angular App
        working-directory: ./frontend
        run: |
          npm install
          sudo sed -i "s#\$API_URL#${{ secrets.API_URL }}#g" src/environments/environment.ts
          cat src/environments/environment.ts
          npm run build

      - name: List Angular Build Output Directory
        working-directory: ./frontend
        run: |
          ls
          pwd
          sudo chmod -R 777 ../backend/public/assets/angular/browser/browser/
          ls -la ../backend/public/assets/angular/browser/browser/


      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: '/home/runner/work/filemanage/filemanage/backend/public/assets/angular/browser/browser'

  deploy_backend:
    name: Deploy Laravel Backend to EC2
    runs-on: ubuntu-latest
    needs: deploy_frontend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: gd

      - name: Install Laravel Dependencies and Create Deployment Package
        working-directory: ./backend
        run: |
          composer install --prefer-dist --no-progress --no-suggest
          zip -r ../backend.zip .
          echo "Listing repository root after zipping:"
          ls -la ..

      - name: Set up SSH Key for SCP and SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Copy Deployment Package to EC2 using native scp
        run: |
          scp -o StrictHostKeyChecking=no backend.zip ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~

      - name: Deploy to EC2 via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /var/www/html/filemanage
            sudo chmod -R 777 /var/www/html/filemanage
            rm -rf *
            unzip -o ~/backend.zip -d /var/www/html/filemanage
            cd /var/www/html/filemanage
            composer install --no-dev --optimize-autoloader


            cat > .env <<'EOL'
          APP_NAME="Document Management"
          APP_ENV=production
          APP_KEY=base64:CmxAqBAGPEZDjWKKS2QetMM2GQlrn9xayPS3b9CMfLE=
          APP_DEBUG=false
          APP_URL=http://localhost
          INSTALLED=1
          APP_VERSION=3.0.0

          LOG_CHANNEL=stack
          LOG_DEPRECATIONS_CHANNEL=null
          LOG_LEVEL=debug

          DB_CONNECTION=mysql
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=3306
          DB_DATABASE=${{ secrets.DB_DATABASE }}
          DB_USERNAME=${{ secrets.DB_USERNAME }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}

          BROADCAST_DRIVER=log
          CACHE_DRIVER=file
          FILESYSTEM_DISK=local
          QUEUE_CONNECTION=sync
          SESSION_DRIVER=file
          SESSION_LIFETIME=120

          MEMCACHED_HOST=127.0.0.1

          REDIS_HOST=127.0.0.1
          REDIS_PASSWORD=null
          REDIS_PORT=6379

          MAIL_MAILER=smtp
          MAIL_HOST=mailhog
          MAIL_PORT=1025
          MAIL_USERNAME=null
          MAIL_PASSWORD=null
          MAIL_ENCRYPTION=null
          MAIL_FROM_ADDRESS="hello@example.com"
          MAIL_FROM_NAME="${APP_NAME}"

          AWS_ACCESS_KEY_ID=
          AWS_SECRET_ACCESS_KEY=
          AWS_DEFAULT_REGION=us-east-1
          AWS_BUCKET=
          AWS_USE_PATH_STYLE_ENDPOINT=false

          PUSHER_APP_ID=
          PUSHER_APP_KEY=
          PUSHER_APP_SECRET=
          PUSHER_HOST=
          PUSHER_PORT=443
          PUSHER_SCHEME=https
          PUSHER_APP_CLUSTER=mt1

          VITE_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
          VITE_PUSHER_HOST="${PUSHER_HOST}"
          VITE_PUSHER_PORT="${PUSHER_PORT}"
          VITE_PUSHER_SCHEME="${PUSHER_SCHEME}"
          VITE_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

          JWT_SECRET=7LX0TJ1VdTiXNuicwATwwDRSxwprVtlVgCph1H2HwsCAjXMAco6knl5sCudc4akP

          JWT_ALGO=HS256

          EOL


            sudo chown apache:apache .env
            sudo chmod 664 .env
            sudo chown -R ec2-user:apache /var/www/html/filemanage
            sudo chmod -R 775 /var/www/html/filemanage
            sudo chmod 664 /var/www/html/filemanage/.env
            php artisan key:generate --force
            php artisan config:clear
            php artisan cache:clear
            sudo systemctl restart httpd
          EOF



