name: Cypress Smoke Test - Production

on:
  workflow_dispatch:

jobs:
  run-e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd frontend/e2e
          npm ci

      - name: Run Cypress tests against PROD
        uses: cypress-io/github-action@v5
        with:
          working-directory: frontend/e2e
          spec: cypress/e2e/spec.cy.ts
          config: baseUrl=https://yourfrontend.com
