name: E2E Smoke Test

on:
  workflow_dispatch:

jobs:
  run-e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd frontend/e2e
          npm ci
          npm install -D typescript ts-node @cypress/webpack-preprocessor @cypress/webpack-dev-server webpack

      - name: Run Cypress Tests on Production
        uses: cypress-io/github-action@v5
        with:
          working-directory: frontend/e2e
          config-file: cypress.config.ts
          browser: electron
          headed: false
          record: false
<<<<<<< HEAD
          spec: cypress/e2e/spec.cy.ts
=======
          spec: cypress/e2e/prod-smoke.cy.ts
>>>>>>> c194017e531bb9150e942ca832054f44c157fe21
          wait-on-timeout: 60

      - name: Upload Cypress videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: frontend/e2e/cypress/videos

      - name: Upload Cypress screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: frontend/e2e/cypress/screenshots
