name: CI/CD- Laravel + Angular (Full Local Test)

on:
  push:
    branches:
      - testing
  workflow_dispatch:

jobs:
  fullstack-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: laravel
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo, pdo_mysql, xml, bcmath, curl, gd

      - name: Setup Composer
        run: composer self-update

      - name: Install Laravel dependencies
        working-directory: ./backend
        run: |
          composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Create .env for Laravel
        working-directory: ./backend
        run: |
          cp .env.example .env || true
          cat > .env <<EOL
          APP_NAME=Laravel
          APP_ENV=local
          APP_KEY=
          APP_DEBUG=true
          APP_URL=http://localhost

          LOG_CHANNEL=stack

          DB_CONNECTION=mysql
          DB_HOST=127.0.0.1
          DB_PORT=3306
          DB_DATABASE=laravel
          DB_USERNAME=root
          DB_PASSWORD=root

          CACHE_DRIVER=file
          SESSION_DRIVER=file
          QUEUE_CONNECTION=sync
          EOL

      - name: Generate Laravel App Key & Run Migrations
        working-directory: ./backend
        run: |
          php artisan config:clear
          php artisan key:generate
          php artisan migrate:fresh --seed --force
          php artisan serve --host=127.0.0.1 --port=8000 &
          sleep 10

      - name: Install Angular dependencies & Build
        working-directory: ./frontend
        run: |
          npm install
          npm run build --
          npx ng serve --port 4200 --host 127.0.0.1 &
          sleep 10

      - name: Install dependencies
        run: |
          cd frontend/e2e
          npm ci
          npm install -D typescript ts-node @cypress/webpack-preprocessor @cypress/webpack-dev-server webpack

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v5
        with:
          working-directory: frontend/e2e
          config-file: cypress.config.ts
          browser: electron
          headed: false
          record: false
          spec: cypress/e2e/testsample.cy.ts
          wait-on-timeout: 60
        